name: クビアカ被害報告
description: 被害情報を報告する
title: "[報告]"
labels:
  - report

body:
  - type: dropdown
    id: species
    attributes:
      label: 樹種
      options:
        - サクラ
        - モモ
        - ウメ
        - スモモ
        - その他

  - type: dropdown
    id: damage
    attributes:
      label: 被害程度
      options:
        - 軽微
        - 中程度
        - 重度

  - type: input
    id: lat
    attributes:
      label: 緯度

  - type: input
    id: lng
    attributes:
      label: 経度

  - type: textarea
    id: memo
    attributes:
      label: 備考
